###
# GET list

GET {{baseUrl}}/tickets?skip=0&limit=10&fields=*
X-Token:{{tokenAdmin}}
Content-Type: application/json

###
# GET by id

GET {{baseUrl}}tickets/5d698738fc93fdd33ada3ef3?fields=*
X-Token:{{tokenAdmin}}
Content-Type: application/json

###
# Bookmark

PUT {{baseUrl}}tickets/5d698738fc93fdd33ada3ef3/bookmark?fields=isBookmark
X-Token:{{tokenAdmin}}
Content-Type: application/json

###
# Remove bookmark

DELETE {{baseUrl}}/tickets/5d698738fc93fdd33ada3ef3/bookmark?fields=isBookmark
X-Token:{{tokenAdmin}}
Content-Type: application/json

###
